services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\AMQP\RecordAMQPMetricsCommand:
    arguments:
      $index: '%env(AMQP_ELASTICSEARCH_INDEX)%'

  App\AMQP\Repository\AMQPQueueMetricsRepository:
    arguments:
        $vhost: '%env(AMQP_MONITORING_VHOST)%'