parameters:
  github.repository_owner:    '%env(GITHUB_REPOSITORY_OWNER)%'
  github.repository_name:     '%env(GITHUB_REPOSITORY_NAME)%'
  github.app_id:              '%env(GITHUB_APP_ID)%'
  github.app_installation_id: '%env(GITHUB_APP_INSTALLATION_ID)%'
  github.rsa_key:             '%env(GITHUB_PRIVATE_RSA_KEY)%'
  github.labels.validation_required: '~validation-required'
  github.labels.in_progress:   ['WIP', 'WAIT', 'Standby']
  github.labels:
    in_progress:             '%github.labels.in_progress%'
    validated:               '~validated'
    validation_environments: ['~validation-blue', '~validation-red', '~validation-green', '~validation-yellow']
    validation_prefix:       '~validation-'
    validation_required:     '%github.labels.validation_required%'
  github.approve_count:       2
  github.default_base_branch: 'dev'
  jira.host:                  '%env(JIRA_HOST)%'
  jira.user:                  '%env(JIRA_USER)%'
  jira.pass:                  '%env(JIRA_PASS)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\:
    resource: '../../src/*'
    exclude: '../../src/{Event,Exception,Helper,Model,Kernel.php}'

  App\Controller\:
    resource: '../../src/Controller'
    tags: ['controller.service_arguments']

  App\Client\GitHubClient:
    arguments:
      $gitHubAppId: '%github.app_id%'
      $gitHubPrivateRsaKey: '%github.rsa_key%'
      $gitHubAppInstallationId: '%github.app_installation_id%'

  App\Client\JiraClient:
    arguments:
      $host: '%jira.host%'
      $username: '%jira.user%'
      $pass: '%jira.pass%'

  App\Factory\JiraIssueFactory:
    arguments:
      $host: '%jira.host%'

  App\Handler\GitHubHandler:
    arguments:
      $labels:            '%github.labels%'
      $approveCount:      '%github.approve_count%'
      $defaultBaseBranch: '%github.default_base_branch%'

  App\Handler\SynchronizationCommand\DeleteValidationRequiredLabelCommand:
    arguments:
      $label: '%github.labels.validation_required%'

  App\Handler\SynchronizationCommand\AddValidationRequiredLabelCommand:
    arguments:
      $label: '%github.labels.validation_required%'

  App\Handler\SynchronizationCommand\TransitionJiraIssueToToValidateCommand:
    arguments:
      $label: '%github.labels.validation_required%'
      $transitionId: 71
      $statusId: 10926

  App\Handler\SynchronizationCommand\TransitionJiraIssueToInReviewCommand:
    arguments:
      $label: '%github.labels.validation_required%'
      $transitionId: 61
      $statusId: 10700

  App\Handler\SynchronizationCommand\TransitionJiraIssueToInProgressCommand:
    arguments:
      $inProgressLabels: '%github.labels.in_progress%'
      $globalTransitionId: 61
      $subTaskTransitions:
        - [statusId: 11021, transitionId: 41]
        - [statusId: 10700, transitionId: 171]
      $subTaskTypeId: 10102
      $statusId: 3

  App\Repository\GitHub\PullRequestRepository:
    arguments:
      $repositoryOwner: '%github.repository_owner%'
      $repositoryName: '%github.repository_name%'

  App\Repository\GitHub\PullRequestReviewRepository:
    arguments:
      $repositoryOwner: '%github.repository_owner%'
      $repositoryName: '%github.repository_name%'

  App\Repository\GitHub\PullRequestLabelRepository:
    arguments:
      $repositoryOwner: '%github.repository_owner%'
      $repositoryName: '%github.repository_name%'

  App\Repository\GitHub\CommitRepository:
    arguments:
      $repositoryOwner: '%github.repository_owner%'
      $repositoryName: '%github.repository_name%'

  public.logger:
    alias: 'logger'
    public: true

  Github\HttpClient\Builder:
  Lcobucci\JWT\Builder:

  JoliCode\Slack\Api\Client:
    factory: ['JoliCode\Slack\ClientFactory', create]
    arguments: ['%env(SLACK_TOKEN)%']

  App\External\HerokuApi:
    arguments:
      $domain: '%heroku.domain%'
      $apiKey: '%heroku.api_key%'

  App\Handler\SlackHandler:
    arguments:
      $token: '%env(SLACK_TOKEN)%'

  App\Dashboard\Query\ReviewEnvironments: '@App\Dashboard\Query\Adapter\FromRepositoryReviewEnvironments'
  App\Dashboard\Query\PullRequestsToDeploy: '@App\Dashboard\Query\Adapter\FromRepositoryPullRequestsToDeploy'
  App\Dashboard\Query\PullRequestsToMergeOnDev: '@App\Dashboard\Query\Adapter\FromRepositoryPullRequestsToMergeOnDev'