name: ğŸ•µï¸ Static code analysis

on: [push]

jobs:
  phpcs:
    name: ğŸ§½ PHP CS
    runs-on: ubuntu-latest
    steps:
      - name: âš™ï¸ Provisioning PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:2.5
        env:
          update: true

      - name: â†˜ï¸ Moving into project
        uses: actions/checkout@v2

      - name: ğŸ“¥ï¸ Installing Composer dependencies
        run: composer install --no-suggest --optimize-autoloader -d tools/php-cs-fixer

      - name: ğŸ§½ PHP CS is keeping code clean
        run: php tools/php-cs-fixer/vendor/bin/php-cs-fixer fix src --rules=@Symfony --verbose --diff --using-cache=no --dry-run
